RotaApp/RotaApp/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	# admin/
    url(r'^admin/', admin.site.urls),

    # accounts/
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # dashboard/
    url(r'dashboard/', include('dashboard.urls', namespace='dashboard')),

    # events/
    url(r'events/', include('events.urls', namespace='events')),

    # meetings/
    url(r'meetings/', include('meetings.urls', namespace='meetings')),

   	# Redirect all other urls
    url(r'^.*$', RedirectView.as_view(url=reverse_lazy('dashboard:index'))),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RotaApp/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

	# /accounts/
	url(r'^$', views.index, name='index'),

	# /accounts/register/
	url(r'^register/$', views.user_register, name='register'),

	# /accounts/login/
	url(r'^login/$', views.user_login, name='login'),

	# /accounts/profile/3/
	url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),

	# accounts/2/edit_user
	url(r'^(?P<user_id>[0-9]+)/edit_user/', views.edit_user, name='user-edit'),

	# accounts/2/delete_user
	url(r'^(?P<user_id>[0-9]+)/delete_user/', views.delete_user, name='user-delete'),

	# /accounts/logout/
	url(r'^logout/$', views.user_logout, name='logout'),
	
]

RotaApp/events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [

	# /events/
	url(r'^$', views.index, name='index'),

	# /events/3/
	url(r'^(?P<event_id>[0-9]+)/$', views.details, name='details'),

	# /events/create/
	url(r'^create/$', views.create_event, name='create'),

	# events/2/edit_event
	url(r'^(?P<event_id>[0-9]+)/edit_event/', views.edit_event, name='event-edit'),

	# events/2/delete_event
	url(r'^(?P<event_id>[0-9]+)/delete_event/', views.delete_event, name='event-delete'),
	
]

RotaApp/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

ROLE_CHOICES = (
		('ADMIN', 'Admin'),
		('MEMBER', 'Member'),
	)

class Member(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='MEMBER')
	phone = models.CharField(max_length=15, unique=True)
	address = models.TextField()
	date_of_birth = models.DateField()
	date_of_joining = models.DateField()
	blood_group = models.CharField(max_length=5)
	designation = models.CharField(max_length=100)

RotaApp/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Member


class UserBasicForm(UserCreationForm):
	email = forms.EmailField(label = "Email")

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name']


class MemberForm(forms.ModelForm):

	date_of_birth = forms.CharField(widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))
	date_of_joining = forms.CharField(widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))

	class Meta:
		model = Member
		fields = ['role', 'phone', 'address', 'date_of_birth', 'date_of_joining', 'blood_group', 'designation']

RotaApp/accounts/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UserBasicForm, MemberForm
from .models import Member

def user_register(request):

    #UserCreationForm(modified into UserBasicForm) does the password checking and other additionals for us
    form = UserBasicForm(request.POST or None)
    member_form = MemberForm(request.POST or None)


    if form.is_valid() and member_form.is_valid():
        user = form.save(commit=False)
        member = member_form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']   #password1 and password2(confirm_password) are the two variables in UserCreationForm 
        email = form.cleaned_data['email']
        user.set_password(password)
        user.save()
       
        user = authenticate(username=username, password=password)

        if user is not None:
        	if user.is_active:
        		member.user = user
        		role = member_form.cleaned_data['role']
        		if role == 'ADMIN':
        			user.is_superuser = True
        		member.save()
        		login(request, user)
        		return render(request, 'dashboard/index.html')
        	else:
        		return render(request, 'accounts/register.html', {'error_message': 'The user is no longer active.'})
    return render(request, 'accounts/register.html', {'form': form, 'member_form': member_form})


def user_login(request):
    # Login required
    if not request.user.is_authenticated:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            #If user is not banned
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'dashboard/index.html', {'success': 'You are now logged in!'})
                else:
                    return render(request, 'accounts/register.html', {'error_message': 'The user is no longer active'})
            return render(request, 'accounts/login.html', {'error': 'Credentials do not match'})
        return render(request, 'accounts/login.html')
    return render(request, 'dashboard/index.html')


def edit_user(request, user_id):
    user = User.objects.get(pk=user_id)

    if request.method == "POST":
        form = UserBasicForm(request.POST, instance=user)
        member_form = MemberForm(request.POST, instance=user.member)

        if form.is_valid() and member_form.is_valid():
            user = form.save(commit=False)
            member = member_form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']   #password1 and password2(confirm_password) are the two variables in UserCreationForm 
            email = form.cleaned_data['email']
            user.set_password(password)
            user.save()

            role = member_form.cleaned_data['role']
            if role == 'Admin':
                user.is_superuser = True
            member.save()
            users = User.objects.all()
            return render(request, 'accounts/index.html', {'users': users})
        return render(request, 'accounts/register.html', {'form': form, 'member_form': member_form})
    else:
        form = UserBasicForm(instance=user)
        member_form = MemberForm(instance=user.member)
        return render(request, 'accounts/register.html', {'form': form, 'member_form': member_form})


def delete_user(request, user_id):
    user = User.objects.get(pk=user_id)
    user.delete()
    users = User.objects.all()
    return render(request, 'accounts/index.html', {'users': users})



def user_logout(request):
    logout(request)
    return render(request, 'accounts/login.html')


def index(request):
    users = User.objects.all()
    if request.user.is_authenticated:
        return render(request, 'accounts/index.html', {'users': users})
    else:
        return render(request, 'accounts/login.html')

def profile(request, user_id):

    # Login required
    if request.user.is_authenticated:
        if user_id:
            return render(request, 'accounts/profile.html', {'user': User.objects.get(pk=user_id), 'user_now': request.user})
        else:
            return render(request, 'accounts/profile.html', {'user': request.user})
    else:
        return render(request, 'accounts/login.html')

RotaApp/accounts/templates/accounts/form_template.html
{% block stylesheets %}
	<style type="text/css">
		input {
			width: 40em;
		}
        select {
            width: 40em;
        }
        textarea {
            width: 40em;
        }
	</style>
{% endblock %}

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small" >{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="=col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

RotaApp/accounts/templates/accounts/index.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Accounts

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<div class="card-header">Accounts</div>
			<div class="card-body">
				<table class="table table-bordered">
					<thead class="thead-dark">
						<th>#</th>
						<th>Username</th>
						<th colspan="2">Actions</th>
					</thead>
					<tbody class="tbody-light">
						{% for user in users %}
							<tr>
								<td>{{ user.id }}</td>
								<td><a href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a></td>
								<td><a href="{% url 'accounts:user-edit' user.id %}" class="btn btn-primary btn-sm">Edit</a></td>
								<td><a href="{% url 'accounts:user-delete' user.id %}" class="btn btn-danger btn-sm">Delete</a></td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

{% endblock %}

RotaApp/accounts/templates/accounts/login.html
{% extends 'dashboard/base.html' %}

{% block title %}Login{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default" style="margin-top: 170px; margin-left: 70px;">
                    <div class="panel-body">

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <form class="form-horizontal" role="form" action="{% url 'accounts:login'%}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_username" maxlength="30" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_password" maxlength="30" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Login</button>
                                </div>
                            </div>
                        </form>

                        <a href="{% url 'accounts:register' %}" style="margin-left: 20px; font-weight: bold; color: black;">Don't have an account? Register here.</a>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

RotaApp/accounts/templates/accounts/member_form.html
{% block stylesheets %}
	<style type="text/css">
		input {
			width: 40em;
		}
        select {
            width: 40em;
        }
        textarea {
            width: 40em;
        }
	</style>
{% endblock %}

{% for field in member_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small" >{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="=col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

RotaApp/accounts/templates/accounts/profile.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Profile

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<div class="card-header">Details</div>
			<div class="card-body">
				<table class="table table-bordered">
					<tbody class="tbody-light">
						<tr>
							<th>#</th>
							<td>{{ user.id }}</td>
						</tr>
						<tr>
							<th>Username</th>
							<td>{{ user.username }}</td>
						</tr>
						<tr>
							<th>Email</th>
							<td>{{ user.email }}</td>
						</tr>
						<tr>
							<th>Phone</th>
							<td>{{ user.member.phone }}</td>
						</tr>
						<tr>
							<th>Address</th>
							<td>{{ user.member.address|linebreaks }}</td>
						</tr>
						<tr>
							<th>Date of Birth</th>
							<td>{{ user.member.date_of_birth }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

{% endblock %}

RotaApp/accounts/templates/accounts/register.html
{% extends 'dashboard/base.html' %}

{% block title %}

	User Form

{% endblock %}

{% block body %}

	<div class="col-md-6 offset-md-3">
		<div class="card">
			<div class="card-header">Register</div>
			<div class="card-body">
				{% if error_message %}
                    <strong>{{ error_message }}</strong>
                {% endif %}

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'accounts/form_template.html' %}
                    {% include 'accounts/member_form.html' %}

                    <div class="form-group">
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>
			</div>
		</div>
	</div>
	

{% endblock %}