RotaApp/RotaApp/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	# admin/
    url(r'^admin/', admin.site.urls),

    # accounts/
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # dashboard/
    url(r'dashboard/', include('dashboard.urls', namespace='dashboard')),

    # events/
    url(r'events/', include('events.urls', namespace='events')),

    # meetings/
    url(r'meetings/', include('meetings.urls', namespace='meetings')),

   	# Redirect all other urls
    url(r'^.*$', RedirectView.as_view(url=reverse_lazy('dashboard:index'))),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RotaApp/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

	# /accounts/
	url(r'^$', views.index, name='index'),

	# /accounts/register/
	url(r'^register/$', views.user_register, name='register'),

	# /accounts/login/
	url(r'^login/$', views.user_login, name='login'),

	# /accounts/profile/3/
	url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),

	# accounts/2/edit_user
	url(r'^(?P<user_id>[0-9]+)/edit_user/', views.edit_user, name='user-edit'),

	# accounts/2/delete_user
	url(r'^(?P<user_id>[0-9]+)/delete_user/', views.delete_user, name='user-delete'),

	# /accounts/logout/
	url(r'^logout/$', views.user_logout, name='logout'),
	
]

RotaApp/dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'

urlpatterns = [

	# /dasboard/
	url(r'^$', views.index, name='index'),
	
]

RotaApp/events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [

	# /events/
	url(r'^$', views.index, name='index'),

	# /events/3/
	url(r'^(?P<event_id>[0-9]+)/$', views.details, name='details'),

	# /events/create/
	url(r'^create/$', views.create_event, name='create'),

	# events/2/edit_event
	url(r'^(?P<event_id>[0-9]+)/edit_event/', views.edit_event, name='event-edit'),

	# events/2/delete_event
	url(r'^(?P<event_id>[0-9]+)/delete_event/', views.delete_event, name='event-delete'),
	
]

RotaApp/dashboard/models.py
from django.db import models

# Create your models here.

RotaApp/dashboard/views.py
from django.shortcuts import render


def index(request):
	return render(request, 'dashboard/index.html')

RotaApp/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheets %}{% endblock %}
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    {# <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/> #}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body>
    
    {% include 'dashboard/navbar.html' %}
    {% include 'dashboard/messages.html' %}

    {% block body %}
    {% endblock %}

</body>
</html>

RotaApp/dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Dashboard

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card-header">Dashboard</div>
		<div class="card">
			<div class="card-body">
				Go ahead, do your thing!
			</div>
		</div>
	</div>

{% endblock %}

RotaApp/dashboard/templates/dashboard/messages.html
{% if success %}

	<div class="alert alert-success">
		{{ success }}
	</div>

{% endif %}

{% if error %}

	<div class="alert alert-danger">
		{{ error }}
	</div>

{% endif %}

RotaApp/dashboard/templates/dashboard/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'dashboard:index' %}">RotaApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:index' %}">Home</a>
          </li>
          {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:index' %}">Accounts</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' request.user.id %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'events:index' %}">Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'meetings:index' %}">Meetings</a>
          </li>

        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }} 
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
          </li>
        </ul>
      {% else %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:register' %}" class="nav-link">Register</a>
          </li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>