RotaApp/RotaApp/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	# admin/
    url(r'^admin/', admin.site.urls),

    # accounts/
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # dashboard/
    url(r'dashboard/', include('dashboard.urls', namespace='dashboard')),

    # events/
    url(r'events/', include('events.urls', namespace='events')),

    # meetings/
    url(r'meetings/', include('meetings.urls', namespace='meetings')),

   	# Redirect all other urls
    url(r'^.*$', RedirectView.as_view(url=reverse_lazy('dashboard:index'))),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RotaApp/events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [

	# /events/
	url(r'^$', views.index, name='index'),

	# /events/3/
	url(r'^(?P<event_id>[0-9]+)/$', views.details, name='details'),

	# /events/create/
	url(r'^create/$', views.create_event, name='create'),

	# events/2/edit_event
	url(r'^(?P<event_id>[0-9]+)/edit_event/', views.edit_event, name='event-edit'),

	# events/2/delete_event
	url(r'^(?P<event_id>[0-9]+)/delete_event/', views.delete_event, name='event-delete'),
	
]

RotaApp/meetings/urls.py
from django.conf.urls import url
from . import views

app_name = 'meetings'

urlpatterns = [

	# /meetings/
	url(r'^$', views.index, name='index'),

	# /meetings/3/
	url(r'^(?P<meeting_id>[0-9]+)/$', views.details, name='details'),

	# /meetings/create/
	url(r'^create/$', views.create_meeting, name='create'),

	# meetings/2/edit_meeting
	url(r'^(?P<meeting_id>[0-9]+)/edit_meeting/', views.edit_meeting, name='meeting-edit'),

	# meetings/2/delete_meeting
	url(r'^(?P<meeting_id>[0-9]+)/delete_meeting/', views.delete_meeting, name='meeting-delete'),
	
]

RotaApp/meetings/models.py
from django.db import models


MEETING_CHOICES = (
		('BOARD', 'Board'),
		('REGULAR', 'Regular'),
	)


class Meeting(models.Model):
	number = models.IntegerField()
	type = models.CharField(max_length=20, choices=MEETING_CHOICES, default='REGULAR')
	agenda = models.TextField()
	date = models.DateField()
	venue = models.CharField(max_length=100)
	time = models.TimeField()
	minutes = models.URLField()
	resolutions = models.TextField(blank=True, null=True)

RotaApp/meetings/forms.py
from django import forms
from .models import Meeting


class MeetingForm(forms.ModelForm):

	date = forms.CharField(widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))
	time = forms.TimeField()

	class Meta:
		model = Meeting
		fields = ['number', 'agenda', 'date', 'venue', 'time', 'minutes', 'resolutions']

RotaApp/meetings/views.py
from django.shortcuts import render
from .forms import MeetingForm
from .models import Meeting


def index(request):
	if request.user.is_authenticated:
		meetings = Meeting.objects.all()
		return render(request, 'meetings/index.html', {'meetings': meetings})


def details(request, meeting_id):
	meeting = Meeting.objects.get(pk=meeting_id)
	return render(request, 'meetings/details.html', {'meeting': meeting})


def create_meeting(request):
    form = MeetingForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        meeting = form.save(commit=False)
        meeting.save()
        return render(request, 'meetings/details.html', {'meeting': meeting})
    return render(request, 'meetings/meeting_form.html', {'form': form})

def edit_meeting(request, meeting_id):
    meeting = Meeting.objects.get(pk=meeting_id)

    if request.method == "POST":
        form = MeetingForm(request.POST, instance=meeting)

        if form.is_valid():
            meeting = form.save(commit=False)
            meeting.save()
            return render(request, 'meetings/details.html', {'meeting': meeting})
    else:
        form = MeetingForm(instance=meeting)
        return render(request, 'meetings/meeting_form.html', {'form': form})

def delete_meeting(request, meeting_id):
    meeting = Meeting.objects.get(pk=meeting_id)
    meeting.delete()
    meetings = Meeting.objects.all()
    return render(request, 'meetings/index.html', {'meetings': meetings})

RotaApp/meetings/templates/meetings/details.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Meeting Details

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<div class="card-header">Meeting Details</div>
			<div class="card-body">
				<table class="table table-bordered">
					<tbody class="tbody-light">
						<tr>
							<th>Number</th>
							<td>{{ meeting.number }}</td>
						</tr>
						<tr>
							<th>Agenda</th>
							<td>{{ meeting.agenda|linebreaks }}</td>
						</tr>
						<tr>
							<th>Date</th>
							<td>{{ meeting.date }}</td>
						</tr>
						<tr>
							<th>Venue</th>
							<td>{{ meeting.venue }}</td>
						</tr>
						<tr>
							<th>Time</th>
							<td>{{ meeting.time }}</td>
						</tr>
						<tr>
							<th>Minutes</th>
							<td>{{ meeting.minutes }}</td>
						</tr>
						{% if meeting.resolutions %}
							<tr>
								<th>Resolutions</th>
								<td>{{ meeting.resolutions|linebreaks }}</td>
							</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

{% endblock %}

RotaApp/meetings/templates/meetings/index.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Meetings

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<div class="card-header">Meetings</div>
			<div class="card-body">
				<table class="table table-bordered">
					<thead class="thead-dark">
						<th>Number</th>
						{% if user.is_superuser %}
							<th colspan="2">Actions</th>
						{% endif %}
					</thead>
					<tbody class="tbody-light">
						{% for meeting in meetings %}
							<tr>
								<td><a href="{% url 'meetings:details' meeting.id %}">{{ meeting.number }}</a></td>
								{% if user.is_superuser %}
									<td><a href="{% url 'meetings:meeting-edit' meeting.id %}" class="btn btn-primary btn-sm">Edit</a></td>
									<td><a href="{% url 'meetings:meeting-delete' meeting.id %}" class="btn btn-danger btn-sm">Delete</a></td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<br>

	{% if user.is_superuser %}
		<div class="text-center">
			<a href="{% url 'meetings:create' %}" class="btn btn-success">Add Meeting</a>
		</div>
	{% endif %}

{% endblock %}

RotaApp/meetings/templates/meetings/meeting_form.html
{% extends 'dashboard/base.html' %}
{% block title %}Meeting form{% endblock %}

{% block body %}

    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header">Meeting Form</div>
            <div class="card-body">

                {% if error_message %}
                    <strong>{{ error_message }}</strong>
                {% endif %}

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'accounts/form_template.html' %}

                    <div class="text-center">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>

                </form>

            </div>
        </div>
    </div>



{% endblock %}