RotaApp/RotaApp/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	# admin/
    url(r'^admin/', admin.site.urls),

    # accounts/
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # dashboard/
    url(r'dashboard/', include('dashboard.urls', namespace='dashboard')),

    # events/
    url(r'events/', include('events.urls', namespace='events')),

    # meetings/
    url(r'meetings/', include('meetings.urls', namespace='meetings')),

   	# Redirect all other urls
    url(r'^.*$', RedirectView.as_view(url=reverse_lazy('dashboard:index'))),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RotaApp/events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [

	# /events/
	url(r'^$', views.index, name='index'),

	# /events/3/
	url(r'^(?P<event_id>[0-9]+)/$', views.details, name='details'),

	# /events/create/
	url(r'^create/$', views.create_event, name='create'),

	# events/2/edit_event
	url(r'^(?P<event_id>[0-9]+)/edit_event/', views.edit_event, name='event-edit'),

	# events/2/delete_event
	url(r'^(?P<event_id>[0-9]+)/delete_event/', views.delete_event, name='event-delete'),
	
]

RotaApp/events/models.py
from django.db import models


class Event(models.Model):
	name = models.CharField(max_length=100, unique=True)
	avenue = models.CharField(max_length=191)
	chair = models.CharField(max_length=100)
	secretary = models.CharField(max_length=100, blank=True, null=True)
	description = models.TextField()
	report = models.URLField(blank=True, null=True)
	remarks = models.TextField()

RotaApp/events/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):

	class Meta:
		model = Event
		fields = ['name', 'avenue', 'chair', 'secretary', 'description', 'report', 'remarks']

RotaApp/events/views.py
from django.shortcuts import render
from .forms import EventForm
from .models import Event


def index(request):
	if request.user.is_authenticated:
		events = Event.objects.all()
		return render(request, 'events/index.html', {'events': events})


def details(request, event_id):
	event = Event.objects.get(pk=event_id)
	return render(request, 'events/details.html', {'event': event})


def create_event(request):
    form = EventForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        event = form.save(commit=False)
        event.save()
        return render(request, 'events/details.html', {'event': event})
    return render(request, 'events/event_form.html', {'form': form})

def edit_event(request, event_id):
    event = Event.objects.get(pk=event_id)

    if request.method == "POST":
        form = EventForm(request.POST, instance=event)

        if form.is_valid():
            event = form.save(commit=False)
            event.save()
            return render(request, 'events/details.html', {'event': event})
    else:
        form = EventForm(instance=event)
        return render(request, 'events/event_form.html', {'form': form})

def delete_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    event.delete()
    events = Event.objects.all()
    return render(request, 'events/index.html', {'events': events})

RotaApp/events/templates/events/details.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Event Details

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<div class="card-header">Event Details</div>
			<div class="card-body">
				<table class="table table-bordered">
					<tbody class="tbody-light">
						<tr>
							<th>#</th>
							<td>{{ event.id }}</td>
						</tr>
						<tr>
							<th>Name</th>
							<td>{{ event.name }}</td>
						</tr>
						<tr>
							<th>Avenue</th>
							<td>{{ event.avenue }}</td>
						</tr>
						<tr>
							<th>Chair</th>
							<td>{{ event.chair }}</td>
						</tr>
						{% if event.secretary %}
							<tr>
								<th>Secretary</th>
								<td>{{ event.secretary }}</td>
							</tr>
						{% endif %}
						<tr>
							<th>Description</th>
							<td>{{ event.description|linebreaks }}</td>
						</tr>
						<tr>
							<th>Report</th>
							<td>{{ event.report }}</td>
						</tr>
						{% if event.remarks %}
							<tr>
								<th>Remarks</th>
								<td>{{ event.remarks|linebreaks }}</td>
							</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

{% endblock %}

RotaApp/events/templates/events/event_form.html
{% extends 'dashboard/base.html' %}
{% block title %}Event form{% endblock %}

{% block body %}

    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header">Event Form</div>
            <div class="card-body">

                {% if error_message %}
                    <strong>{{ error_message }}</strong>
                {% endif %}

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'accounts/form_template.html' %}

                    <div class="text-center">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>

                </form>

            </div>
        </div>
    </div>



{% endblock %}

RotaApp/events/templates/events/index.html
{% extends 'dashboard/base.html' %}

{% block title %}

	Events

{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<div class="card-header">Events</div>
			<div class="card-body">
				<table class="table table-bordered">
					<thead class="thead-dark">
						<th>#</th>
						<th>Name</th>
						{% if user.is_superuser %}
							<th colspan="2">Actions</th>
						{% endif %}
					</thead>
					<tbody class="tbody-light">
						{% for event in events %}
							<tr>
								<td>{{ user.id }}</td>
								<td><a href="{% url 'events:details' event.id %}">{{ event.name }}</a></td>
								{% if user.is_superuser %}
									<td><a href="{% url 'events:event-edit' event.id %}" class="btn btn-primary btn-sm">Edit</a></td>
									<td><a href="{% url 'events:event-delete' event.id %}" class="btn btn-danger btn-sm">Delete</a></td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<br>

	{% if user.is_superuser %}
		<div class="text-center">
			<a href="{% url 'events:create' %}" class="btn btn-success">Add Event</a>
		</div>
	{% endif %}

{% endblock %}